name: Render
on: [pull_request]
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.2.0
        with:
          email: ${{ secrets.RENDER_EMAIL }}
          password: ${{ secrets.RENDER_PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-xxxxxxxxxxxxxxxxxxxx
